### ISSUE TITLE
ESUtlity not Work 

### ISSUE THREAD

**Issue by tornis** [abhishek376/ESUtlilty#1]
Hello,

I'm trying to use the ESUtility to make changes in existing maps in my environment. I performed the procedures described in GitHub but without success. Here is the error:

tornis@linux-eue7:~/tmp/ESUtlilty/target> java -jar ESUtility-full.jar -changeMapping -field total_bytes -clusterName MAILLOG -esHost 10.222.156.76 -mappingType type -newFieldType integer -newIndex logstash-2015.02.25.v2 -oldIndex logstash-2015.02.25
Mar 10, 2015 3:42:18 PM org.elasticsearch.plugins
Informações: [Rigellian Recorder] loaded [], sites []
Scanning old index
7175248 documents found in the logstash-2015.02.25
Reading 100 documents
Exception in thread "main" java.lang.NullPointerException
        at org.allegiance.ESUtility.BufferedClient.flushBatch(BufferedClient.java:42)
        at org.allegiance.ESUtility.BufferedClient.executeESBulk(BufferedClient.java:30)
        at org.allegiance.ESUtility.ChangeMapping.ChangeMapping(ChangeMapping.java:43)
        at org.allegiance.ESUtility.ScanOldIndex.Scan(ScanOldIndex.java:39)
        at org.allegiance.ESUtility.Main.main(Main.java:142)

**Comment by RooseveltAdvisors** [comment]
Hi, @tornis :
I hit the same problem when I was using it today. I fixed it and forked into my own [repo](https://github.com/yuanzhaoYZ/ESUtlilty)

[Commit log](https://github.com/yuanzhaoYZ/ESUtlilty/commit/8172ed1dc8dd857e5d79656988c67a01e7dc0fbb)

**Comment by abhishek376** [comment]
Thanks will take a look :)
